FORMAT: 1A
HOST: http://jiff-config-db.herokuapp.com/api

# Jiff Config API


# Setup

* Fork https://bitbucket.org/Jiff_DT/jiff-navigator/fork

* Work off the src-develop branch

* Open terminal and type `gulp` in your work folder to monitor the changes

* Open new terminal tab and type `chrome --app=http://localhost:8888/release` 

* Do `Cmd` + `i` to open the inspector and resize your view window to `640x1136`


# Central/Develop Process

We are using a Central/Develop git flow process to push changes through production where :

`central https://{your_bitbucket_username}@bitbucket.org/Jiff_DT/jiff-navigator.git (fetch)`

`central https://{your_bitbucket_username}@bitbucket.org/Jiff_DT/jiff-navigator.git (push)`

And 

`origin https://rinatjiff@bitbucket.org/{your_username}/jiff-navigator.git (fetch)`

`origin https://rinatjiff@bitbucket.org/{your_username}/jiff-navigator.git (push)`

The steps are :

* Push to your origin

* Create a pull request to `central/src-develop`


## config [/]

Use this endpoint to generate the main config.json to drop in your jsons folder.

### config [GET]

+ Response 200 (application/json)

        {
            "mode": "dev",
            "username": "...",
            "place": 1,
            "paths": {
                "paths_id": "original",
                "central": "jiff-navigator",
                "prod": "jiff-prod",
                "release": "release",
                "base": "...",
                "dropbox": "...",
                "place": 1
            },
            "versions":"...",
            "menu_items":"...",
            "store":"...",
            "cards":"...",
            "action_cards":"...",
            "questions":"...",
            "rewards_center":"...",
            "onboarding_questions":"...",
            "interests":"...",
            "programs":"..."
        }






## WIP create version [/create/version/{?name,blackstatusbar,dashboard,tabs,defaulttab,menu,menu_style,logo,rewards_center,web,background_web,displayed_name,place,video_name,has_terms,has_phone,on_boarding,personal_assessment}]

Use this endpoint to create a new version.

### WIP create [GET]

+ Parameters
    + name (string) - version name (snake_case)
    + blackstatusbar (boolean, optional) - statusbar type
        + default: true
    + dashboard (boolean, optional) - activate home stream
        + default: false
    + tabs (optional) - deprecated
    + defaulttab (optional) - first tab after recommendation
    + menu (optional) - list of more menu items
    + menu_style (optional) - "dark" or "light" style
        + default: "light"
    + logo (optional) - image name (png, jpg or svg)
    + rewards_center(optional) - list of rewards
    + web (optional) - wip
    + background_web (optional) - wip
    + displayed_name (optional) - version name (display friendly)
    + place (number,optional) - order
    + video_name (optional) - intro video name
    + has_terms (boolean, optional) - disable terms screen
    + has_phone (boolean, optional) - disable phone capabilities
    + on_boarding (optional) - list of slide names
    + personal_assessment (boolean,optional) - disable health assessment
        +default: true

+ Response 200 (application/json)

        {
            "name": "datacore",
            "blackstatusbar": true,
            "dashboard": false,
            "tabs": [
                "stream",
                "me",
                "explore",
                "rewards"
            ],
            "defaulttab": "stream",
            "menu": [
                "home_stream",
                "notifications",
                "news_feed",
                "program_catalog",
                "settings",
                "directory",
                "store",
                "help"
            ],
            "menu_style": "dark",
            "logo": "logo-datacore.png",
            "rewards_center": null,
            "web": false,
            "background_web": null,
            "displayed_name": "Life Central",
            "place": 1,
            "video_name": null,
            "has_terms": null,
            "has_phone": null,
            "on_boarding": null,
            "personal_assessment": true
        }


## WIP create user [/create/user/{?name,maxtimelines,version,dob,feet,inch,lbs,zip,timeline,total,sex,lp,onboarding_questions,interests,explore_types,explore_sections,rewards,hsa,store,credit,place,recommended_programs,additional_programs,emails}]

Use this endpoint to create a new user.

### WIP create [GET]

+ Parameters
    + name (string) - version name (lowercase)
    + maxtimelines (number, optional) - max number of timelines
    + version (string, optional) - version name user belongs to
    + dob (number, optional) - date of birth (year/month/day)
    + feet (number, optional) - height (.ft)
    + inch (number, optional) - height (.in)
    + lbs (number, optional) - weight (.lbs)
    + zip (number, optional) - zip code
    + timeline (number, optional) - default timeline index
    + total (number, optional) - deprecated
    + sex (string, optional) - gender (f or m)
    + lp (string, optional) - custom landing page
    + onboarding_questions (array[string], optional) - array of question ids 
    + interests (array[string], optional) - array of interests
    + explore_types (array[string], optional) - array of explore section types
    + explore_sections (array[string], optional) - array of explore sections (program ids list is between "")
    


+ Response 200 (application/json)

        {
            "name": "ellis stevens",
            "maxtimelines": 3,
            "version": "datacore",
            "dob": "1990-04-03T00:00:00.000Z",
            "feet": 5,
            "inch": 9,
            "lbs": 175,
            "zip": 94043,
            "timeline": 0,
            "total": 2500,
            "sex": "m",
            "lp": null,
            "onboarding_questions": null,
            "interests": null,
            "explore_types": [
                "search",
                "programs",
                "resources",
                "list"
            ],
            "explore_sections": [
                "",
                "",
                "bcbs_BR,delta_dental,vsp,employee_assistance",
                "content_center,event_center,store,newsfeed"
            ],
            "rewards": [
                "pw_20",
                "hsa_100",
                "cycling_kit",
                "buy_nutribullet",
                "buy_amazon",
                "buy_rei",
                "buy_jiff",
                "buy_spaweek",
                "buy_netflix",
                "buy_platejoy",
                "raffle_tdf",
                "raffle_rio",
                "raffle_yoga",
                "charity_MOD",
                "charity_DWB",
                "charity_STC",
                "charity_TIT"
            ],
            "hsa": false,
            "store": [
                "healthkit_app",
                "fitbit_blaze",
                "fitbit_alta",
                "caloryguard",
                "garmin_vivoactive",
                "misfit_shine",
                "fitbit_aria",
                "withings_activite",
                "moves_app"
            ],
            "credit": 40,
            "place": 23,
            "recommended_programs": [
                "get_active",
                "hello_wallet",
                "zipongo",
                "sleep_soundly_generic"
            ],
            "enrolled_programs": [
                "quest",
                "hra"
            ],
            "additional_programs": [
                "mequilibrium"
            ],
            "emails": null
        }




