FORMAT: 1A
HOST: http://jiff-config-db.herokuapp.com/config

# Jiff Config API


# Setup

* Fork https://bitbucket.org/Jiff_DT/jiff-navigator/fork

* Work off the src-develop branch

* Open terminal and type `gulp` in your work folder to monitor the changes

* Open new terminal tab and type `chrome --app=http://localhost:8888/release` 

* Do `Cmd` + `i` to open the inspector and resize your view window to `640x1136`


# Central/Develop Process

We are using a Central/Develop git flow process to push changes through production where :

`central https://rinatjiff@bitbucket.org/Jiff_DT/jiff-navigator.git (fetch)`
`central https://rinatjiff@bitbucket.org/Jiff_DT/jiff-navigator.git (push)`

and 

`origin https://rinatjiff@bitbucket.org/{your_username}/jiff-navigator.git (fetch)`
`origin https://rinatjiff@bitbucket.org/{your_username}/jiff-navigator.git (push)`

The steps are :

* Push to your origin

* Create a pull request to `central/src-develop`



Use this endpoint to generate the main config.json to drop in your jsons folder.

## config [/]

### config [GET]

+ Response 200 (application/json)

        {
            "mode": "dev",
            "username": "rinatjiff",
            "place": 1,
            "paths": {
                "paths_id": "original",
                "central": "jiff-navigator",
                "prod": "jiff-prod",
                "release": "release",
                "base": "http://jiff-navigator-db.herokuapp.com/",
                "dropbox": "https://dl.dropboxusercontent.com/",
                "place": 1
            },
            "versions":"...",
            "menu_items":"...",
            "store":"...",
            "cards":"...",
            "action_cards":"...",
            "questions":"...",
            "rewards_center":"...",
            "onboarding_questions":"...",
            "interests":"...",
            "programs":"..."
        }






## WIP create version [/create/version/{?name,blackstatusbar,dashboard}]

Use this endpoint to create new version.

### WIP create [GET]

+ Parameters
    + name (string) - version name
    + blackstatusbar (boolean) - statusbar type
    + dashboard (boolean) - activate home stream

+ Response 200 (application/json)

        {
            "name": "datacore",
            "blackstatusbar": true,
            "dashboard": false,
            "tabs": [
            "stream",
            "me",
            "explore",
            "rewards"
            ],
            "defaulttab": "stream",
            "menu": [
            "home_stream",
            "notifications",
            "news_feed",
            "program_catalog",
            "settings",
            "directory",
            "store",
            "help"
            ],
            "menu_style": "dark",
            "logo": "logo-datacore.png",
            "rewards_center": null,
            "web": false,
            "background_web": null,
            "displayed_name": "Life Central",
            "place": 1,
            "video_name": null,
            "has_terms": null,
            "has_phone": null,
            "on_boarding": null,
            "personal_assessment": true
        }


