FORMAT: 1A
HOST: http://jiff-config-db.herokuapp.com/config

# config

Use this api to generate the main config.json to drop in your jsons folder.

## config [/]

### config [GET]

+ Response 200 (application/json)
{
  "mode": "dev",
  "username": "rinatjiff",
  "place": 1,
  "paths": {
    "paths_id": "original",
    "central": "jiff-navigator",
    "prod": "jiff-prod",
    "release": "release",
    "base": "http://jiff-navigator-db.herokuapp.com/",
    "dropbox": "https://dl.dropboxusercontent.com/",
    "place": 1
  },
  "versions":"...",
  "menu_items":"...",
  "store":"...",
  "cards":"...",
  "action_cards":"...",
  "questions":"...",
  "rewards_center":"...",
  "onboarding_questions":"...",
  "interests":"...",
  "programs":"..."
}